spring:
  datasource:
#    driver-class-name: com.mysql.jdbc.Driver
#    username: root
#    password: root
#    url: jdbc:mysql://localhost:3306/competitive?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8&useSSL=false&allowMultiQueries=true
    driver-class-name: com.mysql.jdbc.Driver
    username: jc
    password: root
    url: jdbc:mysql://49.4.4.105:3306/competitive?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8&useSSL=false&allowMultiQueries=true

logging:
  level:
    com.xinzuo.competitive.dao : debug


oos:
  endpoint: oss-cn-beijing.aliyuncs.com
  keyid:    LTAI0A2P2eeZOVsz # 填写刚刚生成的AccessKey
  keysecret: M7UQsljzUtMqRJAJoWkkPFEMsZREXA  # 填写刚刚生成的Accesssecret
  bucketname: xinzuolvyou # bucket名称
  filehost: images    #bucket下文件夹的路径

mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
